config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

  resources :categories, except: [:destroy]
end

app/models/Article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/Category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: true
end

app/models/User.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  # before_save { self.email = email.downcase }
  # Popracowac nad magic numbers
  validates :username, presence: true,
                       uniqueness: true,
                       length: { minimum: 3, maximum: 25 }
  validates :email, presence: true,
                    length: { maximum: 105 },
                    uniqueness: { case_sensitivity: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'You must be logged in to perform that action.'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.find(current_user.id)
    if @article.save
      flash[:notice] = 'Article has been successfully created.'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:notice] = 'Article has been successfully deleted.'
    redirect_to articles_path
  end

  def edit; end

  def update
    @article.user = User.find(current_user.id)
    if @article.update(article_params)
      flash[:notice] = 'The article has been successfully updated.'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:notice] = 'You can only edit or delete your own articles.'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update show destroy]
  before_action :require_admin, except: %i[index show]
  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category has been successfully created.'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'The category has been successfully updated.'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:notice] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in.'
      redirect_to user_path(user)
    else
      flash.now[:notice] = 'Invalid credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have logged out.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash['notice'] = 'Your accountt has been successfully updated.'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    if @user == current_user
      flash[:notice] = 'Your account and all your articles have been delted'
      session[:user_id] = nil
      redirect_to root_path
    else
      flash[:notice] = 'User and all articles created by user have been successfully deleted'
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    unless current_user == @user || current_user.admin?
      flash[:notice] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:notice] = 'Only admin users can perform that action'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
  <% obj.each do |article| %>
  <tr>
    <td><%= link_to article.title, article_path(article) %></td>
    <td><%= article.description %></td>
    <td><% article.categories.each do |category| %>
     <%= "#{category.name}; "  %>
    <% end %></td>
    <td><%= article.user.username if article.user %></td>
    <td><%= time_ago_in_words(article.created_at) %> ago</td>
    <td><%= time_ago_in_words(article.updated_at) %> ago</td>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
    <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary" %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
  </tr>
  <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/validation_errors', obj: @article %>

<%= form_for @article  do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
<br>
  <%= form.label :description %>
  <%= form.text_area :description %>
<br>
  <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "form-check-inline form-check") { cb.check_box(class: "form-check-input") + cb.text } %>
  <% end %>
<br>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title, "Edit Article" %>
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back to articles listing', articles_path %>

app/views/articles/index.html.erb
<% content_for :title, "Articles" %>

<h1>Listing All Articles</h1>
<%= link_to 'Create new article', new_article_path %>

<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Categories</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
  </tr>
  <%= render 'article', obj: @articles %>
</table>
<div class="text-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<% content_for :title, "New Article" %>
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back to articles listing', articles_path %>

app/views/articles/show.html.erb
<% content_for :title, "Show Article" %>
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>
<% if @article.categories.any? %>
<p>Categories: </p>
<ul>
<% @article.categories.each do |category| %>
<li><%= link_to category.name, category_path(category) %></li>
<% end %>
</ul>
<% end %>
<p>Created by: <%= link_to @article.user.username, user_path(@article.user) %></p>
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
<%= link_to 'Edit this article', edit_article_path(@article) %> |
<%= link_to 'Delete this article', article_path(@article), method: :delete %> |
<% end %>
<%= link_to 'Back to articles listing', articles_path %>

app/views/categories/_form.html.erb
<%= render 'shared/validation_errors', obj: @category %>

<%= form_for @category  do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
<br>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Edit Category" %>
<h1>Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>
<h1>Listing All Categories</h1>
<% if logged_in? && current_user.admin? %>
<%= link_to 'New Category', new_category_path %>
<% end %>

<div class="row">
  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th>Number of articles</th>
      <th></th>
      <th></th>
    </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category) %></td>
      <td><%= pluralize(category.articles.count, 'article') %> </td>
      <% if logged_in? && current_user.admin? %>
      <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary" %></td>
      <td><%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
      <% else %>
      <td></td>
      <td></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>
<div class="text-center">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<% content_for :title, "New Category" %>
<h1 class="text-center">New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<% content_for :title, "Show Category" %>
<h1>Category: <%= @category.name  %></h1>

<% if logged_in? && current_user.admin? %>
<div>
  <%= link_to 'Edit category name', edit_category_path(@category) %> | 
  <%= link_to 'Delete category', category_path(@category), method: :delete %>
</div>
<% end %>

<div class="mt-3">
  <table class="table table-hover">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Categories</th>
      <th>Created by</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
    </tr>
    <%= render 'articles/article', obj: @category_articles %>
  </table>
<div>
<div class="text-center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
    <div class="alert alert-info text-center" role="alert">
      <%= msg %>
    </div>
    <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><i class="fa fa-shower" aria-hidden="true"></i> Shower Blog</a>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if logged_in? %>
      <li class="nav-item">
        <a class="nav-link" href="/articles">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/categories">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users">Users</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Your profile <%= "Admin" if current_user.admin? %></a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <a class="dropdown-item" href="<%= edit_user_path(current_user) %>">Edit profile</a>
          <a class="dropdown-item" href="<%= user_path(current_user) %>">View your profile</a>
        </div>
      </li>
      </ul>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
      <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li><%= link_to 'Log in', login_path, class: "nav-link" %></li>
      <li><%= link_to 'Sign up', signup_path, class: "nav-link" %></li>      
    <%  end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "Shower Blog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <%= render '/layouts/messages' %>
    
    <div class="container">
      <%= yield %>
      <% if Rails.env.development? %>
      <div class="text-center">
        <%= debug(params) %>
      </div>
      <% end %>
    </div>

    <hr>
    <footer class="text-center">
        <p>&copy; <%= Time.current.year %> - Shower Blog </p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="jumbotron text-center text-light">
  <h1 class="display-3"><i class="fa fa-shower" aria-hidden="true"></i> Shower Blog</h1>
  <p class="lead">The cleanest blog out there</p>
  <hr class="my-2">
  <p>More info</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/signup" role="button">Sign up now</a>
  </p>
</div>

app/views/shared/_validation_errors.html.erb
<% if obj.errors.any? %>
<h2>The following errors prevented the form from being submitted:</h2>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/validation_errors', obj: @user %>

<%= form_for @user  do |f| %>
  <div class="form-group">
    <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, class: "form-control", placeholder: "E-mail" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-block") %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Edit Account" %>
<h1 class="text-center">Edit Account</h1>
<div class="row">
  <div class="col-md-8 col-lg-4 offset-md-2 offset-lg-4">
<%= render 'form'%>
  </div>
</div>

app/views/users/index.html.erb
<% content_for :title, "Users" %>
<h1 class="text-center">All Bloggers</h1>
<div class="row">
  <table class="table table-hover">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.username, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= time_ago_in_words(user.created_at) %> ago</td>
    <td><%= time_ago_in_words(user.updated_at) %> ago</td>
    <% if logged_in? && (current_user == user || current_user.admin?) %>
    <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %></td>
    <td><%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
    <% else %>
    <td></td>
    <td></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>

app/views/users/new.html.erb
<% content_for :title, "Sign Up" %>
<h1 class="text-center">Sign Up for Shower Blog</h1>
<div class="row">
  <div class="col-md-8 col-lg-4 offset-md-2 offset-lg-4">
    <%= render 'form'%>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, "Show User" %>
<h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-4 offset-md-4 text-center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 class="text-center mt-3"><%= @user.username%>'s articles</h4>

<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
  </tr>
 <%= render 'articles/article', obj: @user_articles %>
 </table>
 <div class="text-center">
  <%= will_paginate @user_articles %>
</div>